export const currencies = [
  { key: "USD", code: "USD", symbol: "$", name: "US Dollar" },
  { key: "EUR", code: "EUR", symbol: "€", name: "Euro" },
  { key: "GBP", code: "GBP", symbol: "£", name: "British Pound" },
  { key: "JPY", code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { key: "AUD", code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { key: "CAD", code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  { key: "CHF", code: "CHF", symbol: "CHF", name: "Swiss Franc" },
  { key: "CNY", code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { key: "INR", code: "INR", symbol: "₹", name: "Indian Rupee" },
  { key: "NZD", code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { key: "ZAR", code: "ZAR", symbol: "R", name: "South African Rand" },
  { key: "MXN", code: "MXN", symbol: "$", name: "Mexican Peso" },
  { key: "SGD", code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { key: "HKD", code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { key: "KRW", code: "KRW", symbol: "₩", name: "South Korean Won" },
  { key: "BRL", code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { key: "RUB", code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { key: "SEK", code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { key: "NOK", code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { key: "DKK", code: "DKK", symbol: "kr", name: "Danish Krone" },
  { key: "PLN", code: "PLN", symbol: "zł", name: "Polish Zloty" },
  { key: "THB", code: "THB", symbol: "฿", name: "Thai Baht" },
  { key: "TRY", code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { key: "PHP", code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { key: "IDR", code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { key: "MYR", code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { key: "VND", code: "VND", symbol: "₫", name: "Vietnamese Dong" },
  { key: "EGP", code: "EGP", symbol: "E£", name: "Egyptian Pound" },
  { key: "ILS", code: "ILS", symbol: "₪", name: "Israeli Shekel" },
  { key: "AED", code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham" },
  { key: "SAR", code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  { key: "KWD", code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" }
];
